services:
  db:
    image: postgres:16
    container_name: easypizza_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: easypizza_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@easypizza.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: easypizza_api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ../easypizza
      dockerfile: Dockerfile
    container_name: easypizza_frontend
    ports:
      - "3333:3333"
    volumes:
      - ../easypizza/src:/app/src
      - ../easypizza/public:/app/public
      - ../easypizza/index.html:/app/index.html
      - ../easypizza/vite.config.ts:/app/vite.config.ts
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api
    restart: unless-stopped

volumes:
  postgres_data:
